name: mark wagenaar
favicon: null
layout_spectrum: 0.61253
typography_spectrum: 0.24356
title: pictografie - all about the visual
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#020202'
    - '#fefefe'
    - '#3c3c3c'
    - '#636363'
    - '#c5c5c5'
  brandStrength: 0.5
  lightness: 0.4793090608436614
  saturation: 0.35589740332216024
  rhythmicContrast: 0.75
purpose: []
